# Generated by Django 4.2.5 on 2023-10-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hang_man', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifes', models.IntegerField(default=3)),
                ('original_word', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Letter',
            new_name='Letters',
        ),
        migrations.RenameField(
            model_name='letters',
            old_name='letter',
            new_name='letters',
        ),
    ]
