# Generated by Django 4.2.5 on 2023-10-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hang_man', '0002_game_rename_letter_letters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='guessed_word',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='lifes',
            field=models.IntegerField(),
        ),
    ]
